### ISSUE TITLE
Is this assembly? is this?

### ISSUE THREAD

**Issue by d1snin** [smokeytube/nitrotypebot#2]
is this assembly?

**Comment by smokeytube** [comment]
Mhm.

**Comment by d1snin** [comment]
my face when

**Comment by d1snin** [comment]
i will leave the webhook spammer running for hours if you reopen this again

https://github.com/smokeytube/nitrotypebot/blob/fb707a3da929c91ad39b1ee4842deb75e2a7ac1e/main.py#L70

**Comment by smokeytube** [comment]
This webhook is from a server that has been deleted for 1 year and 1 month

**Comment by d1snin** [comment]
😭😭😭😭😭😭

**Comment by d1snin** [comment]
Undelivered Mail Returned to Sender
16 мар. 2022, 23:13
КОМУ
ПАПКА:
Входящие
This is the mail system at host mail.yandex.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

You can find the the possible reasons of the undelivered message letter here:
https://yandex.com/support/mail-new/wizard/zout_send/not-got…

Please, do not reply to this message.


<reply+aqic7vixkbdgvt3jwzj7qm6ah5z33evbnhhdxdqonm@reply.github.com>: host
    in-9.smtp.github.com[140.82.112.31] said: 501 5.1.7 Bad sender address
    syntax (in reply to MAIL FROM command)

Reporting-MTA: dns; forward500p.mail.yandex.net
X-Yandex-Queue-ID: C32CBF02D70
X-Yandex-Sender: rfc822; -@d1s.dev
Arrival-Date: Wed, 16 Mar 2022 23:12:58 +0300 (MSK)

Final-Recipient: rfc822; reply+aqic7vixkbdgvt3jwzj7qm6ah5z33evbnhhdxdqonm@reply.github.com
Original-Recipient: rfc822;reply+aqic7vixkbdgvt3jwzj7qm6ah5z33evbnhhdxdqonm@reply.github.com
Action: failed
Status: 5.1.7
Remote-MTA: dns; in-9.smtp.github.com
Diagnostic-Code: smtp; 501 5.1.7 Bad sender address syntax

**Comment by Davr1** [comment]
:3

**Comment by smokeytube** [comment]
we're going to get our accounts disabled again for messing around

**Comment by d1snin** [comment]
so true zach

**Comment by d1snin** [comment]
I'm currently persisting in your walls.
